### ISSUE TITLE
Make "Join Listserve" button 

### ISSUE THREAD

**Issue by greensteph** [GSA/citizenscience.gov#106]

**Comment by greensteph** [comment]
Need to re-visit @JohnMcLaughlinGSA 

- placement

- language

**Comment by afomi** [comment]
@greensteph - what'd you have in mind here? 

My guess would be a button link and some text describing the ListServ.

**Comment by greensteph** [comment]
This needs a discussion on placement and language. Will put back on the agenda, thanks.
