### ISSUE TITLE
Link to resources from About Page

### ISSUE THREAD

**Issue by JohnMcLaughlinGSA** [GSA/citizenscience.gov#115]
@greensteph , please modify the second sentence of the  About page (https://www.citizenscience.gov/about/) to make the following words hyperlinks:
* "a catalog" - link to the Catalog,
* "a toolkit" - link to the Toolkit, and  
* "gateway to a community" - link to the Communities page

**Comment by greensteph** [comment]
@JohnMcLaughlinGSA This update has been made.
