### ISSUE TITLE
Add EPA Handbook into Catalog

### ISSUE THREAD

**Issue by JohnMcLaughlinGSA** [GSA/citizenscience.gov#223]
Please add "EPA Quality Assurance Handbook and Guidance Documents for Citizen Science Projects" (hyperlink to https://www.epa.gov/citizen-science/quality-assurance-handbook-and-guidance-documents-citizen-science-projects) to out Toolkit in two places:
1) In the Resources collection under the  "Prepare a Data Management Plan" section of "Step 4 — Manage Your Data" (https://www.citizenscience.gov/toolkit/howto/step4/#prepare); and
2) Under the "Project Design" heading of the "Toolkits and Guides" section of the Resource Library (https://www.citizenscience.gov/toolkit/resource-library/#)

Thanks!

John

**Comment by greensteph** [comment]
Closed by #225
