### ISSUE TITLE
Add two-pager to About page

### ISSUE THREAD

**Issue by JohnMcLaughlinGSA** [GSA/citizenscience.gov#238]
Please post the pdf two-pager I sent via email on our site's About page (https://www.citizenscience.gov/about/) in a new sentence added to the end of the first paragraph that states: "You can learn more about the activities of the Federal Community of Practice on Crowdsourcing and Citizen Science in this {two-page overview document <=hyperlink to the document}."

**Comment by greensteph** [comment]
Closed by #240
