### ISSUE TITLE
Switch out accent color

### ISSUE THREAD

**Issue by greensteph** [GSA/citizenscience.gov#248]
Replace med blue (#0071bc) when used with the dark blue background (#112e51) with orange (#e87853). 

Use a white hover color for each. 

for :visited state use #e87853.

*toolkit-home.md --> <section> starts line 76

create a class to assign these styles:   .banner-tagline-accent-color
      -add to _banners.scss file
     - a {
  color: orange;
  &:hover {
    color: white;
  }
  &:active {
    color: white;
  }
  &:visited {
    color: orange;
  }
}

**Comment by Mel-Leusch** [comment]
closed by #258
