### ISSUE TITLE
Update Join Listserve info to Digital.gov COP page

### ISSUE THREAD

**Issue by greensteph** [GSA/citizenscience.gov#272]
Suggestion from Sophia Liu:
JOIN FedCCS Listserv by sending an email to: FCPCCS-subscribe-request@listserv.gsa.gov

**Comment by sophiabliu-usgs** [comment]
We are also wondering if it is easy to change the name of the listserv to FedCCS so that it is consistent with how we describe it. Would that affect the listserv emails? Could FCPCCS listserv email point to a new FedCCS listserv? Would all the information on subscribers and pots still be preserved when switching from FCPCCS@listserv.gsa.gov to FedCCS@listserv.gsa.gov?

**Comment by greensteph** [comment]
@sophiabliu-usgs I do not manage the Listserve. I believe it was Ruthanna. Do you know who she passed management permissions on to?
CC: @jarahameador

**Comment by sophiabliu-usgs** [comment]
She passed it to me. I figured I need to talk with the GSA Listserv folks to follow up on my question.

Thanks, Sophia
____________________

Sophia B Liu, Ph.D.
Innovation Specialist  ||  Open Innovation Lead  ||  Crowdsourcing & Citizen Science Coordinator
Co-Chair of Federal Community for Crowdsourcing & Citizen Science (FedCCS)​
U.S. Geological Survey (USGS) Science and Decisions Center
The National Center || 12201 Sunrise Valley Drive || Reston, VA 20192, USA

703-261-3057 (cell)  ||  Teams Chat (DOI Bureaus Only)
SophiaLiu@usgs.gov<mailto:%20sophialiu@usgs.gov>  ||  OpenInnovation@usgs.gov<mailto:openinnovation@usgs.gov>
      FEMA-Crowdsourcing@fema.dhs.gov<mailto:FEMA-Crowdsourcing@fema.dhs.gov>
LinkedIn<https://www.linkedin.com/in/sophiabliu/>  ||  Twitter<https://twitter.com/sophiabliu>  ||  Facebook<https://www.facebook.com/sophiabliu>  (sophiabliu)

CitizenScience.gov<https://www.citizenscience.gov>   ||   Join FedCCS Listserv<https://digital.gov/communities/crowdsourcing-citizen-science/>   ||   Chall​enge.gov<https://www.challenge.gov/>
Open Innovation Community Wiki<https://my.usgs.gov/confluence/display/cdi/Open+Innovation+Community>  ||  Join Open Innovation Listserv<https://listserv.usgs.gov/mailman/listinfo/cdi-openinnovation>
USGS Open Innovation Teams Site<https://teams.microsoft.com/l/team/19%3aee13de3f499f409f88d75a4652ec366c%40thread.skype/conversations?groupId=4e99c117-dca7-44e4-9ca7-716c80b49ca3&tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494> (Only Accessible to DOI Bureaus)
           [cid:2ae23b46-772c-44db-800f-e770573f0a2e] <https://www.citizenscience.gov/>
[cid:548ac13c-a986-4be0-99ff-e8b3554ca14e]<https://www.usgs.gov/energy-and-minerals/science-and-decisions-center/science/cowdsourcing-citizen-science-open>
________________________________

**Comment by greensteph** [comment]
Email address edit made here [https://github.com/GSA/digitalgov.gov/pull/2322](https://github.com/GSA/digitalgov.gov/pull/2322)

I cannot update the associated text "_JOIN_ **FedCCS** _Listserv_" as it is templated for all communities.
