### ISSUE TITLE
Need site description

### ISSUE THREAD

**Issue by greensteph** [GSA/citizenscience.gov#41]
@JohnMcLaughlinGSA need this: 

A description of your website that will show up in search indexes and social media shares.

Currently:
Citizenscience.gov is an official government website designed to accelerate the use of crowdsourcing and citizen science across the U.S. government.

Keep or replace?

**Comment by JohnMcLaughlinGSA** [comment]
I say keep. Thanks for checking.  I mean the description is accurate for what the site is currently designed to do, but please let me know if you have any concerns about it.

**Comment by greensteph** [comment]
sound good!
