### ISSUE TITLE
Pages Vulnerability Report Fixes - 3512

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/citizenscience.gov#429]
- [x] Remediate Pages vulnerability scan issues for citizenscience.gov: https://pages.cloud.gov/report/3512

**Comment by jairoanaya** [comment]
The findings on the report 3512 where considered "false negative".  The project looks compliant. See new report https://pages.cloud.gov/report/4470

**Comment by jairoanaya** [comment]
@r-bartlett-gsa this card can be closed. No changes were made.
