### ISSUE TITLE
Need to test for broken links on each Toolkit How-To step page

### ISSUE THREAD

**Issue by greensteph** [GSA/citizenscience.gov#57]

**Comment by BalajiJBcs** [comment]
The following URL is broken and the information is given below to the specific broken line

1. Vimeo Link is broken in line - [Link] (https://github.com/GSA/citizenscience.gov/blob/d0a2fcd5f8a2ad9c7c15627fe1a0cf06bb868bdc/_how-to-steps/Step-1-scope-out-your-problem.html#L13)

2.  What specific techniques are available  - [Link] (https://github.com/GSA/citizenscience.gov/blob/d0a2fcd5f8a2ad9c7c15627fe1a0cf06bb868bdc/_how-to-steps/Step-1-scope-out-your-problem.html#L61)

3. Guide to Choosing and Using Citizen Science (Centre for Ecology and Hydrology, PDF) - [Link]
(https://github.com/GSA/citizenscience.gov/blob/d0a2fcd5f8a2ad9c7c15627fe1a0cf06bb868bdc/_how-to-steps/Step-1-scope-out-your-problem.html#L87)

4. Structuring Interdisciplinary Research Management (Journal Article, 2013) - [Link] 
(https://github.com/GSA/citizenscience.gov/blob/d0a2fcd5f8a2ad9c7c15627fe1a0cf06bb868bdc/_how-to-steps/Step-1-scope-out-your-problem.html#L91)

5. Transdisciplinary Research in Sustainability Science (Journal Article, 2013) - [Link]
(https://github.com/GSA/citizenscience.gov/blob/d0a2fcd5f8a2ad9c7c15627fe1a0cf06bb868bdc/_how-to-steps/Step-1-scope-out-your-problem.html#L93)

6.  Frameworks for citizen science - [Link]
(https://github.com/GSA/citizenscience.gov/blob/d0a2fcd5f8a2ad9c7c15627fe1a0cf06bb868bdc/_how-to-steps/Step-1-scope-out-your-problem.html#L130)

**Comment by greensteph** [comment]
@BalajiJBcs Thanks so much for your help with these!

**Comment by greensteph** [comment]
- [x] Step 1

- [ ] Step 2

- [ ] Step 3

- [ ] Step 4

- [ ] Step 5

**Comment by BalajiJBcs** [comment]
Let me know do I need to fix any errors. I couldn't get what Step 1 .... to Step 5. @greensteph
