### ISSUE TITLE
Need to test for broken links on each Toolkit Case Study page

### ISSUE THREAD

**Issue by greensteph** [GSA/citizenscience.gov#58]

**Comment by BalajiJBcs** [comment]
Here are the pages

i) In the **air-sensor-toolbox.html** page

1. Podcast for Air Quality (https://github.com/GSA/citizenscience.gov/blob/9eca77d56a0b71f4d1b59116cbae79e5be65c6ec/_case-study/air-sensor-toolbox.html#L58)

ii) In the ** citizen-archivist.html** page
 
1.U.S. National Archives Team on the Amara Platform
(https://github.com/GSA/citizenscience.gov/blob/9eca77d56a0b71f4d1b59116cbae79e5be65c6ec/_case-study/citizen-archivist.html#L52)
