### ISSUE TITLE
Edit table of Coordinators to be put on new Coordinators Page

### ISSUE THREAD

**Issue by JohnMcLaughlinGSA** [GSA/citizenscience.gov#66]
@greensteph, please edit the table that currently sits on the [Communities page](https://www.citizenscience.gov/community/) (soon to be moved to the new Coordinators page) such that:
* The USDA Coordinator is changed to "Jim Kahler"
* The NOAA Coordinator is changed to "Laura Oremland"
* The FDA Coordinator is changed to "Elaine Johanson"
* The BLM Coordinator is changed to "Mara Alexander"
* The row column for OSTP is deleted

The revised table should match this one: https://docs.google.com/spreadsheets/d/1FM_Z_3Y3sEv8UFTzMPPN-3UPHm20BQY8Oft6LH0zeFY/edit#gid=0

**Comment by greensteph** [comment]
@JohnMcLaughlinGSA I've made the update on the dev site. Will update the live site after the data freeze is lifted.
