### ISSUE TITLE
Find or create Case Study pdf for Ebird: Crowdsourcing Bird Data

### ISSUE THREAD

**Issue by greensteph** [GSA/citizenscience.gov#67]
is not on current site https://crowdsourcing-toolkit.sites.usa.gov/ebird-bird-data/

**Comment by JohnMcLaughlinGSA** [comment]
I created a new pdf of the case study.  it is at:
https://drive.google.com/a/gsa.gov/file/d/1KuteSOyMJ78UPiuvIZSjC26D-Jcg_hqn/view?usp=sharing

Please use that one.
